gui:
  nerdFontsVersion: "3"
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  showFileTree: true
  showRandomTip: false
  showCommandLog: false
  theme:
    activeBorderColor:
      - "#f5c56e"
      - bold
    inactiveBorderColor:
      - "#686868"
    searchingActiveBorderColor:
      - "#59c2ff"
      - bold
    optionsTextColor:
      - "#bfbdb6"
    selectedLineBgColor:
      - "#23211b"
    cherryPickedCommitBgColor:
      - "#2e2a1a"
    cherryPickedCommitFgColor:
      - "#f5c56e"
    unstagedChangesColor:
      - "#f06b73"
    defaultFgColor:
      - "#bfbdb6"
git:
  log:
    showGraph: always
    order: topo-order
  pagers:
    - colorArg: always
      pager: delta --side-by-side --paging=never
